### ISSUE TITLE
Task1 - Zolotuhin

### ISSUE THREAD

**Issue by and-se** [and-se/1kurs-vesna-2018#2]
**По времени жизни переменных**

> процессор считает эту память свободной и переписывает значение в ней

Ну, процессор ничего не считает. Какая там память свободная, решает операционная система.

Так объясните подробнее, что происходит с переменной внутри вызываемой функции. Адреса, смена значения по одному адресу - это всё правильные аргументы, но где вывод про то, что же происходит с переменными внутри функции?

**Comment by MrFang** [comment]
@and-se Fixed
