### ISSUE TITLE
Task 2 - Zolotuhin

### ISSUE THREAD

**Issue by and-se** [and-se/1kurs-vesna-2018#4]
Отлично!

Единственное - раз Вы уже умеете делать модули, так почему бы описанные в начале main.cpp функции:

> void help();
> void write (IntArray array);
> void move (IntArray array , int direct);
> void sort (IntArray array, int direct);
> void put (IntArray array, int index, int value);
> void reverse (IntArray array); 

- не вынести в отдельный модуль, ну например IntArrUtils.h. Тут правда вопрос про функцию put (она делает индекс от 1) - это наверно лишнее для Utils... Ну да ладно, это на будущее.

**Comment by and-se** [comment]
Ещё замечание - не нужно в структуре IntArray хранить длину массива в динамической переменной - это лишняя опасность забыть освободить память. Раз Вы точно знаете размер данных (а это int), так заведите "обычное" поле int size.

**Comment by MrFang** [comment]
@and-se Все функции объявленные внутри main -- наследие прошлого семестра. По факту это просто программа, которую я писал в том полугодии только приспособленная под другой массив

**Comment by MrFang** [comment]
@and-se put можно исправить. Индекс от 1 для удобства пользователя, но можно i-1 делать в тексте main

**Comment by and-se** [comment]
Можете не исправлять уже, это на будущее.

P.S. Словарь Даля вечером посмотрю, с ходу не завёлся.

**Comment by MrFang** [comment]
@and-se Исправил тип данных в структуре
