### ISSUE TITLE
Task 1 - Mestnikova Ayaana

### ISSUE THREAD

**Issue by ayafester** [and-se/1kurs-vesna-2018#7]

**Comment by and-se** [comment]
Не пишите в выводах конспект исходного кода - надо тезисно изложить, зачем Вы написали именно такой код и что он конкретно доказывает.

По первой задаче - надо бы заключить, что несмотря на то, что переменные в функциях outer_func и inner_func называются одинаково (int a), это разные переменные, т.к. мы видели эффект с "восстановлением" значения переменной в outer_func. Значит, переменная действительно видима только в своём блоке.

Относительно второй задачи. Надо бы написать, что раз значение в памяти было перезаписано, значит эта память на момент вывода свободна. Если этой области памяти соответствовала бы переменная, память была бы занята, и следовательно не была бы перезаписана.
Но мы наблюдаем иное, посему из всей этой логики заключаем, что переменной на момент последнего вывода на экран уже не существует. Наиболее вероятным объяснением является как раз то, что переменная живёт только внутри блока, в котором она объявлена. В нашем случае таким блоком является тело функции inner_func.
